name: themoverx
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  google_fonts: ^2.1.0
  flutter_screenutil: ^5.0.0+2
  carousel_pro: ^1.0.0
  flutter_swiper: ^1.1.6
  sliding_sheet: ^0.3.7
  vertical_card_pager: ^1.5.0
  horizontal_card_pager: ^1.1.1
  google_maps_flutter: ^0.5.24+1
  geolocator: ^7.7.0
  geocoder: ^0.2.1
  location: ^4.3.0
  google_maps_webservice: ^0.0.19
  google_place: ^0.4.3
  intl: ^0.17.0
  flutter_polyline_points: ^1.0.0
  flutter_google_places: ^0.3.0
  auto_size_text: ^2.1.0
  geocoding: ^2.0.1





dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash.png
    - assets/images/splash2.png
    - assets/images/splash3.png
    - assets/images/logo.png
    - assets/images/Emini.png
    - assets/images/EGo.png
    - assets/images/executive.png
    - assets/images/s1.png
    - assets/images/s2.gif
    - assets/images/s3.jpg
    - assets/images/s4.jpg
    - assets/images/ic_money.png
    - assets/images/ic_transact.png
    - assets/images/ic_reward.png
    - assets/images/ic_send.png
    - assets/images/wallet_logo.png
    - assets/images/carousel_flight_discount.png
    - assets/images/carousel_hotel_discount.png
    - assets/images/carousel_covid_discount.png
    - assets/images/banner.png
    - assets/images/banner2.jpg
    - assets/images/destination_bali.png
    - assets/images/destination_paris.png
    - assets/images/destination_rome.png
    - assets/images/eauto.png
    - assets/images/ebike.png
    - assets/images/city_to_city.png
    - assets/images/householder.png
    - assets/images/creative.png
    - assets/images/Retailers.png
    - assets/images/ss.jpg
    - assets/images/car.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
