name: themovers
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.5
  firebase_auth: ^3.3.4
  firebase_database: ^9.0.3
  google_fonts: ^2.1.0
  flutter_staggered_grid_view: ^0.4.0
  provider: ^5.0.0
  flushbar: ^1.10.4
  intl: ^0.17.0
  flutter_swiper: ^1.1.6
  flutter_svg: ^0.20.0-nullsafety.3
  google_maps_flutter: ^2.1.1
  geolocator: ^8.0.1
  geocode: ^1.0.1
  geocoder: ^0.2.1
  http: ^0.13.4
  permission_handler: ^8.3.0
  pinput: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

